# docker-compose build
# configured for CSE3DMS - Database Management System
# La Trobe University
# Created by Kiki Adhinugraha

# how to use:
# make sure you have Docker or Docker Desktop installed
# remove "postgis_" from the filename. Make sure the file name is "docker-compose.yml"
# Open the folder that contains docker-compose.yml
# run C:\> docker-compose up

version: '2.0'

services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474 
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687 
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "C:/dataset/neo4j/data:/data"
      - "C:/dataset/neo4j/logs:/logs"
      - "C:/dataset/neo4j/import:/import"
      - "C:/dataset/neo4j/plugins:/plugins"      
